version: '3.7'

volumes:
  kong_data: {}

networks:
  kong-net:
    external: false

services:

  kong:
    #build: .
    image: "${KONG_DOCKER_TAG:-kong/kong:3.7-rhel}"
    user: "${KONG_USER:-kong}"
    environment:
      KONG_DECLARATIVE_CONFIG: /opt/conf/kong.yml
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_DATABASE: 'off'
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PLUGINS: basic-auth,kong-service-gateway
      KONG_LOG_LEVEL: 'debug'
      CC_USER1: 'REDACTED'
      CC_PW1: 'REDACTED'
      CC_USER2: 'RDCTD'
      CC_PW2: 'RDCTD''
    networks:
      - kong-net
    ports:
      - "8000:8000/tcp"
      - "127.0.0.1:8001:8001/tcp"
      - "8443:8443/tcp"
      - "127.0.0.1:8444:8444/tcp"
    volumes:
      - .:/opt/conf
    command: sh /opt/conf/build.sh

  producer:
    networks:
      - kong-net
    image: python:3.8-slim
    volumes:
      - ./producer:/app
      - ./platformatory_kafka:/app/platformatory_kafka
    working_dir: /app
    command: tail -f /dev/null


  consumer:
    image: python:3.8-slim
    volumes:
      - ./consumer:/app
      - ./platformatory_kafka:/app/platformatory_kafka
    working_dir: /app
    command: tail -f /dev/null
    networks:
      - kong-net
